"""Init file for sparkle."""
import sparkle.about as about
import sparkle.configurator as configurator
import sparkle.instance as instance
import sparkle.platform as platform
import sparkle.solver as solver
import sparkle.structures as structures
import sparkle.tools as tools
import sparkle.types as types
