#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: continuumio/miniconda3:latest

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: Test
            caches:
              - pip
              - condacache
            script:
              - conda info
              - conda env create -f environment.yml 
              - conda activate sparkle
              - pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
              - pip install flake8
              - flake8 
        - step:
            name: Sonar cube
            script:
              - pipe: sonarsource/sonarcloud-scan:1.2.1
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
              
definitions:
  caches:
    condacache: /opt/conda/pkgs

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly