#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: continuumio/miniconda3:latest

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          cache:
            - pip
            - condacache
            - condacache-root
          script:
            - conda info
            - conda env create -f environment.yml 
            - conda activate sparkle
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          cache:
            - pip
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - flake8 

definitions:
  caches:
    condacache: /opt/conda/pkgs
    condacache-root: /root/.conda/pkgs
