#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: continuumio/miniconda3:latest

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - pwd
            - ls -la
            - conda env create -f environment.yml 
            - conda activate sparkle
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - flake8 . --extend-exclude=dist,build,Commands --no-show-source --statistics
