name: sparkle-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Basic conda install
  - python=3.9
  - swig=3.0
  - gnuplot
  - latexmk
  - pip
  - pip:
    - --editable .  # self install !
    - runrunner @ git+https://bitbucket.org/sparkle-ai/runrunner.git@main#egg=runrunner
    # For Sparkle
    - numpy
    - pandas
    # Upcoming pandas requirement (Pandas 3.0), remove once 3.0 has arrived
    - pyarrow
    # Testing
    - pytest
    - pytest-mock==3.10.0
    - flake8==5.0.4
    - flake8-quotes==3.3.1
    - flake8-bandit==4.1.1
    - pep8-naming==0.13.2
    - flake8-docstrings==1.6.0
    - flake8-use-fstring==1.4.0
    - flake8-use-pathlib==0.3.0
    - flake8-annotations==3.0.1
    # For AutoFolio
    - aslib-scenario @ git+https://github.com/mlindauer/ASlibScenario
    - xgboost
    - scikit-learn==1.3.2
    - ConfigSpace
    - smac>=2.0.0
    - scipy
    - pynisher 
    # To build documentation
    - -r Documentation/requirements.txt
