name: sparkle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - swig=3.0
  - gnuplot
  - pip
  - pytest=6.2
  - flake8=3.9
  - pip:
    - git+https://github.com/mlindauer/ASlibScenario
    - certifi==2021.5.30
    - click==8.0.1
    - cloudpickle==1.6.0
    - ConfigSpace==0.4.19
    - Cython==0.29.24
    - dask==2021.7.0
    - distributed==2021.7.0
    - fsspec==2021.7.0
    - HeapDict==1.0.1
    - joblib==1.0.1
    - lazy-import==0.2.2
    - liac-arff==2.5.0
    - locket==0.2.1
    - msgpack==1.0.2
    - numpy==1.21.1
    - pandas==1.3.0
    - partd==1.2.0
    - psutil==5.8.0
    - pynisher==0.6.4
    - pyparsing==2.4.7
    - pyrfr==0.8.2
    - python-dateutil==2.8.2
    - pytz==2021.1
    - PyYAML==5.4.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - six==1.16.0
    - smac==0.13.1
    - sortedcontainers==2.4.0
    - tblib==1.7.0
    - threadpoolctl==2.2.0
    - toolz==0.11.1
    - tornado==6.1
    - xgboost==1.4.2
    - zict==2.0.0
