name: sparkle-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - swig=3.0
  - gnuplot
  - pytest
  - flake8
  - pip
  - pip:
    # For Sparkl
    - numpy
    - pandas
    # For AutoFolio
    - aslib-scenario @ git+https://github.com/mlindauer/ASlibScenario
    - xgboost
    - scikit-learn
    - ConfigSpace
    - smac
    - scipy==1.6.3  # 1.7.x removed a private function used by smac
