name: sparkle
channels:
  - conda-forge
  - defaults
variables: # runsolver compilation
  CPATH: "'$CONDA_PREFIX/include:$CPATH'"
  LDPATH: "'$CONDA_PREFIX/lib'"
dependencies:
  - python=3.9
  - swig=3.0
  - gnuplot
  - libnuma # runsolver compilation
  - numactl # runsolver compilation
  - pip
  - pip:
    - --editable .  # self install !
    - RunRunner==0.1.3
    - attrs==23.2.0
    - certifi==2024.2.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - ConfigSpace==0.7.1
    - dask==2024.3.1
    - distributed==2024.3.1
    - flake8==5.0.4
    - flake8-quotes==3.3.1
    - flake8-bandit==4.1.1 
    - pep8-naming==0.13.2
    - flake8-docstrings==1.6.0
    - flake8-use-fstring==1.4.0
    - flake8-use-pathlib==0.3.0
    - flake8-annotations==3.0.1
    - fsspec==2024.3.1
    - iniconfig==2.0.0
    - joblib==1.3.2
    - liac-arff==2.5.0
    - locket==1.0.0
    - mccabe==0.7.0
    - msgpack==1.0.8
    - numpy==1.26.4
    - packaging==24.0
    - pandas==2.2.1
    - partd==1.4.1
    - pluggy==1.4.0
    - psutil==5.9.8
    - pyarrow==15.0.2
    - pycodestyle==2.9.1
    - pyflakes==2.5.0
    - pynisher==1.0.10
    - pyparsing==3.1.2
    - pyrfr==0.9.0
    - pytest==8.1.1
    - pytest-mock==3.10.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - PyYAML==6.0.1
    - scikit-learn==1.3.2
    - scipy==1.12.0
    - six==1.16.0
    - smac==2.0.2
    - sortedcontainers==2.4.0
    - tblib==3.0.0
    - threadpoolctl==3.4.0
    - toolz==0.12.1
    - tornado==6.4
    - xgboost==2.0.3
    - zict==3.0.0
