name: sparkle
channels:
  - conda-forge
  - defaults
variables: # runsolver compilation
  CPATH: "'${CONDA_PREFIX}/include:$CPATH'"
  LDPATH: "'${CONDA_PREFIX}/lib'"
dependencies:
  - python=3.10
  - swig=4.0.2 # SMAC3 C++ compiler
  - gnuplot # Only used for reports
  - libnuma # runsolver compilation
  - numactl # runsolver compilation
  - pip
  - pip:
    - --editable .  # Devtools self install
    - flake8==5.0.4 # Devtools
    - flake8-quotes==3.3.1 #Devtools
    - flake8-bandit==4.1.1 #Devtools
    - pep8-naming==0.13.2 #Devtools
    - flake8-docstrings==1.6.0 #Devtools
    - flake8-use-fstring==1.4.0 #Devtools
    - flake8-use-pathlib==0.3.0 #Devtools
    - flake8-annotations==3.0.1 #Devtools
    - pytest==8.1.1 # Devtools
    - pytest-mock==3.10.0 # Devtools
    - pre-commit==3.7.1 # Devtools
    - threadpoolctl==3.4.0 # Devtools Pytest
    #- python-dateutil==2.9.0.post0
    #- liac-arff==2.5.0 # Autofolio
    #- scikit-learn==1.3.2 # AutoFolio
    #- xgboost==2.0.3 # AutoFolio
    #- smac==2.2.0 # AutoFolio
    #- pyarrow==15.0.2 # Extension of pandas to read/write parquet files