name: sparkle
channels:
  - conda-forge
  - defaults
variables: # runsolver compilation
  CPATH: "'${CONDA_PREFIX}/include:$CPATH'"
  LDPATH: "'${CONDA_PREFIX}/lib'"
dependencies:
  - python=3.10
  - swig=4.0.2 # SMAC3 C++ compiler
  - libnuma=2.0.18 # runsolver compilation
  - numactl=2.0.18 # runsolver compilation
  - r-base=4.4.1  # R installation for IRACE
  - pip # Sparkle installation
  - pip:
    - SparkleAI
