name: sparkle-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - swig=3.0
  - texlive-core
  - gnuplot
  - pip
  - pip:
    # For Sparkle numpy
    - pandas
    # For AutoFolio
    -  aslib-scenario @ git+https://github.com/mlindauer/ASlibScenario
    -  xgboost
    -  scikit-learn
    -  ConfigSpace
    -  smac
    -  scipy==1.6.3  # 1.7.x removed a private function used by smac
    # Requirements for sparkle documentation build
    -  Sphinx
    -  recommonmark
    -  sphinx-bootstrap-theme
    -  sphinx-rtd-theme
    -  sphinxcontrib-applehelp
    -  sphinxcontrib-devhelp
    -  sphinxcontrib-htmlhelp
    -  sphinxcontrib-jsmath
    -  sphinxcontrib-qthelp
    -  sphinxcontrib-serializinghtml
