name: sparkle
channels:
  - conda-forge
  - defaults
variables: # runsolver compilation
  CPATH: "'${CONDA_PREFIX}/include:$CPATH'"
  LDPATH: "'${CONDA_PREFIX}/lib'"
dependencies:
  - python=3.10
  - swig=4.0.2 # SMAC3 C++ compiler
  - gnuplot # Only used for reports
  - libnuma # runsolver compilation
  - numactl # runsolver compilation
