# Experimental Mac Environment, not all Sparkle commands may run correctly.
name: sparkle-mac
channels:
  - conda-forge
  - defaults
dependencies:
  # Basic conda install
  - python=3.9
  - gnuplot
  - pip
  - pip:
    # For Sparkle
    - --editable .  # self install !
    - swig==4.0.2 #Changed from 3.0 to 3.0.6
    - numpy
    - pandas
    - RunRunner==0.1.3
    # Testing
    - pytest
    - pytest-mock==3.10.0
    - flake8==5.0.4
    - flake8-quotes==3.3.1
    - flake8-bandit==4.1.1
    - pep8-naming==0.13.2
    - flake8-docstrings==1.6.0
    - flake8-use-fstring==1.4.0
    - flake8-use-pathlib==0.3.0
    - flake8-annotations==3.0.1
    # For AutoFolio
    - aslib-scenario @ git+https://github.com/mlindauer/ASlibScenario
    - xgboost
    - scikit-learn
    - ConfigSpace
    - smac
    #- scipy==1.6.3  # TODO: Fix when Autofolio is updated
    - pynisher<1.0  # smac requirement
    - scikit-learn<1.1.0  # 1.1.0 contains a fix for SimpleImputer that breaks AutoFolio
    # To build documentation
    - latexmk.py # Mac requires the .py extension, while linux does not
    - -r Documentation/requirements.txt
