name: sparkle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - swig=3.0
  - texlive-core
  - gnuplot
  - pip
  - pip:
    - alabaster==0.7.12
    - git+https://github.com/mlindauer/ASlibScenario
    - Babel==2.9.1
    - certifi==2021.5.30
    - chardet==4.0.0
    - click==8.0.1
    - cloudpickle==1.6.0
    - commonmark==0.9.1
    - ConfigSpace==0.4.19
    - Cython==0.29.23
    - dask==2021.6.2
    - distributed==2021.6.2
    - docutils==0.16
    - fsspec==2021.6.1
    - HeapDict==1.0.1
    - idna==2.10
    - imagesize==1.2.0
    - Jinja2==3.0.1
    - joblib==1.0.1
    - lazy-import==0.2.2
    - liac-arff==2.5.0
    - locket==0.2.1
    - MarkupSafe==2.0.1
    - msgpack==1.0.2
    - numpy==1.21.0
    - packaging==21.0
    - pandas==1.3.0
    - partd==1.2.0
    - psutil==5.8.0
    - Pygments==2.9.0
    - pynisher==0.6.4
    - pyparsing==2.4.7
    - pyrfr==0.8.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - PyYAML==5.4.1
    - recommonmark==0.7.1
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - six==1.16.0
    - smac==0.13.1
    - snowballstemmer==2.1.0
    - sortedcontainers==2.4.0
    - Sphinx==4.0.3
    - sphinx-bootstrap-theme==0.7.1
    - sphinx-rtd-theme==0.5.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tblib==1.7.0
    - threadpoolctl==2.1.0
    - toolz==0.11.1
    - tornado==6.1
    - urllib3==1.26.6
    - xgboost==1.4.2
    - zict==2.0.0
