name: Badge Generator

on: # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

jobs:
  Code-Tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.14'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y python=3.10.14 # https://github.com/conda/conda/issues/13560#issuecomment-1992720842
        conda env update --file dev-env.yml --name base
        pip install genbadge[tests,coverage]
    - name: Run Code Coverage report
      run:  pytest --all --cov sparkle/ --cov-report=xml:.reports/coverage/coverage.xml
    - name: Run badge generator coverage
      run: genbadge coverage -i .reports/coverage/coverage.xml -o .reports/coverage/coverage-badge.svg
    - name: Run tests report
      run: pytest --all --junitxml=.reports/junit/junit.xml
    - name: Create tests badge
      run: genbadge tests -i .reports/junit/junit.xml -o .reports/junit/junit-badge.svg
    - name: Commit to branch
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com";
        git config --global user.name "github-actions[bot]";
        git diff --quiet .reports/coverage || git add .reports/coverage
        git diff --quiet .reports/junit || git add .reports/junit
        git diff --quiet .reports/ || { git commit -m "Update badge"; git push; }

    - name: Archive outputs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
       name: output
       path: Output/
       retention-days: 5
