name: CodeCoverage

on: [push]

jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.14'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y python=3.10.14 # https://github.com/conda/conda/issues/13560#issuecomment-1992720842
        conda env update --file dev-env.yml --name base
        pip install genbadge[coverage]
    - name: Run Code Coverage report
      run: pytest --cov sparkle/ --cov-report=xml
    - name: Run badge generator
      run: genbadge coverage -i coverage.xml -o .reports/coverage/coverage-badge.svg
    - name: Commit to branch
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

    - name: Archive outputs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
       name: output
       path: Output/
       retention-days: 5
